---
title: "Wild git collaboration practice!"
author: "your names here!"
date: "1/25/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## STEP 5: No merge conflicts!

```{r partner 1}
### In this code chunk, start with the diamonds dataset (built in to
### ggplot2 package) and create a plot of price vs. carat (or some other
### variables of your choice)

ggplot(diamonds, aes(x=carat,y=price)) + 
  geom_point()

```

```{r partner 2}
### In this code chunk, start with the diamonds dataset (built in to
### ggplot2 package) and create a subset based on filtering, e.g., 
### size greater than 1 carat or cut is "Ideal"

diamond_subset <- diamonds %>% 
  filter(cut == "Ideal")

```

## STEP 7: Uh oh, merge conflicts!

```{r break-it-1}
breaking code is fun!

  ## comment comment

```

## STEP 11: And even more merge conflicts!

```{r break-it-2}
code about diamonds
shiny shiny diamonds
# random comment about precious gems


```
